spring.application.name=svc-inventory
server.port=8083

spring.datasource.url=jdbc:postgresql://db-inventory:5432/db_inventory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

menu.service.url=http://svc-menu:8081
